name: CI

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux x64, os: ubuntu-24.04 }
          - { name: Linux arm64, os: ubuntu-24.04-arm }
          - { name: Windows x64, os: windows-2025 }
          - { name: Windows arm64, os: windows-11-arm }
          - { name: macOS, os: macos-15 }
        dotnet:
          - { name: .NET 8, version: "8.0.x" }
          - { name: .NET 9, version: "9.0.x" }
          - { name: .NET 10, version: "10.0.x" }

    steps:
      - name: Check out SFML.Net
        uses: actions/checkout@v6

      - name: Setup .NET ${{ matrix.dotnet.version }} SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - name: Enforce SDK Version
        run: dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }} --force
      - name: Verify SDK Installation
        run: dotnet --info
        continue-on-error: true

      - name: Install SFML.Net Dependencies
        run: dotnet restore
      - name: Build SFML.Net
        run: dotnet build --configuration Release --no-restore
      - name: Test SFML.Net
        if: matrix.dotnet.name == '.NET 8'
        run: dotnet test --configuration Release --no-restore
      - name: Pack SFML.Net
        run: dotnet pack --configuration Release -o Publish

      - name: Install SFML.Net Examples Dependencies
        run: dotnet restore examples/Examples.sln
      - name: Build SFML.Net Examples
        run: dotnet build --configuration Release --no-restore examples/Examples.sln

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: SFML.Net (${{ matrix.platform.name }} ${{ matrix.dotnet.name }})
          path: Publish/SFML.*.*.nupkg